version: '3.8'

services:
  share:
    image: alfresco/alfresco-share:25.2.0.46
    container_name: alfresco-share
    environment:
      REPO_HOST: alfresco-repo
      REPO_PORT: 8080
      JAVA_OPTS: >-
        -Xms256m -Xmx1g
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        -Dcsrf.filter.enabled=false
    ports:
      - "8180:8080"
    volumes:
      - ./javascript-console-share/target/javascript-console-share-0.7-SNAPSHOT.jar:/usr/local/tomcat/webapps/share/WEB-INF/lib/javascript-console-share-0.7-SNAPSHOT.jar
    networks:
      - alfresco-network

networks:
  alfresco-network:
    external: true
