version: '3.8'

services:
  share:
    image: alfresco/alfresco-share:25.2.0.46
    environment:
      REPO_HOST: alfresco
      REPO_PORT: 8080
    ports:
      - "8180:8080"
    depends_on:
      - alfresco
    volumes:
      - ./javascript-console-share/target/javascript-console-share-0.7-SNAPSHOT.jar:/usr/local/tomcat/webapps/share/WEB-INF/lib/javascript-console-share-0.7-SNAPSHOT.jar
