<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.fmaul</groupId>
  <artifactId>javascript-console</artifactId>
  <version>0.7-SNAPSHOT</version>
  <name>JavaScript Console - SDK 4.13.0-A8</name>
  <description>JavaScript Console for Alfresco 25.2.0 Community</description>
  <packaging>pom</packaging>
  <prerequisites>
    <maven>3.3.0</maven>
  </prerequisites>
  <properties>
    <!-- Alfresco Maven Plugin version to use -->
    <alfresco.sdk.version>4.13.0-A8</alfresco.sdk.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Properties used in dependency declarations -->
    <alfresco.groupId>org.alfresco</alfresco.groupId>
    <alfresco.bomDependencyArtifactId>acs-community-packaging</alfresco.bomDependencyArtifactId>
    <alfresco.platform.version>25.2.0</alfresco.platform.version>
    <alfresco.share.version>25.2.0.46</alfresco.share.version>
    <!-- Docker images -->
    <docker.acs.image>alfresco/alfresco-content-repository-community</docker.acs.image>
    <docker.share.image>alfresco/alfresco-share</docker.share.image>
    <!-- JRebel Hot reloading of classpath stuff and web resource stuff -->
    <jrebel.version>1.1.8</jrebel.version>
  </properties>
  <!-- Libs used in Unit and Integration tests -->
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>4.2.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- The main Alfresco Repo dependency for compiling Java code in src/main/java -->
    <dependency>
      <groupId>${alfresco.groupId}</groupId>
      <artifactId>alfresco-remote-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- Bring in Alfresco RAD so we get access to AlfrescoTestRunner classes -->
    <dependency>
      <groupId>org.alfresco.maven</groupId>
      <artifactId>alfresco-rad</artifactId>
      <version>${alfresco.sdk.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <!-- This will import the dependencyManagement for all artifacts in the selected Alfresco platform.
                 NOTE: You still need to define dependencies in your POM, but you can omit version as
                       it's enforced by this dependencyManagement.
            -->
      <dependency>
        <groupId>${alfresco.groupId}</groupId>
        <artifactId>${alfresco.bomDependencyArtifactId}</artifactId>
        <version>${alfresco.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Redefine the following Share dependencies as they have different version numbers than platform. -->
      <dependency>
        <groupId>${alfresco.groupId}</groupId>
        <artifactId>share</artifactId>
        <version>${alfresco.share.version}</version>
        <type>war</type>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>${alfresco.groupId}</groupId>
        <artifactId>share</artifactId>
        <version>${alfresco.share.version}</version>
        <classifier>classes</classifier>
        <scope>provided</scope>
      </dependency>
      <dependency>
        <groupId>${alfresco.groupId}</groupId>
        <artifactId>alfresco-web-framework-commons</artifactId>
        <version>${alfresco.share.version}</version>
        <classifier>classes</classifier>
        <scope>provided</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <pluginManagement>
      <plugins>
        <!-- Filter resources in any sub-project with this config -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.1.0</version>
          <configuration>
            <encoding>UTF-8</encoding>
            <nonFilteredFileExtensions>
              <nonFilteredFileExtension>ftl</nonFilteredFileExtension>
              <nonFilteredFileExtension>acp</nonFilteredFileExtension>
              <nonFilteredFileExtension>svg</nonFilteredFileExtension>
              <nonFilteredFileExtension>pdf</nonFilteredFileExtension>
              <nonFilteredFileExtension>js</nonFilteredFileExtension>
            </nonFilteredFileExtensions>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.zeroturnaround</groupId>
          <artifactId>jrebel-maven-plugin</artifactId>
          <version>${jrebel.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>3.0.0-M1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>3.1.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <!-- Make sure resources in sub-projects are filtered -->
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>
  <profiles>
    <profile>
      <id>java17</id>
      <activation>
        <jdk>[17,21)</jdk>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.11.0</version>
            <configuration>
              <release>17</release>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>java21</id>
      <activation>
        <jdk>[21,)</jdk>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.11.0</version>
            <configuration>
              <release>21</release>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
  <!--
        Alfresco Maven Repositories
        -->
  <repositories>
    <repository>
      <id>alfresco-public</id>
      <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
    </repository>
    <repository>
      <id>alfresco-public-snapshots</id>
      <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
      </snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>alfresco-plugin-public</id>
      <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
    </pluginRepository>
    <pluginRepository>
      <id>alfresco-plugin-public-snapshots</id>
      <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>daily</updatePolicy>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
  <modules>
    <module>javascript-console-repo</module>
    <module>javascript-console-share</module>
  </modules>
</project>
